<?php

namespace Paymob\Payment\Plugin\Adminhtml;

use Magento\Config\Block\System\Config\Form;
use Magento\Framework\App\Config\ScopeConfigInterface;
use Magento\Framework\Data\Form\Element\Fieldset;
use Magento\Config\Model\Config\Structure\Element\Group;
use Magento\Framework\App\Config\ScopeConfigInterface as ScopeType;

class AddDynamicMethodsPlugin
{
    protected $scopeConfig;

    public function __construct(ScopeConfigInterface $scopeConfig)
    {
        $this->scopeConfig = $scopeConfig;
    }

    public function afterInitFields(
        Form $subject,
        $result,
        Fieldset $fieldset,
        Group $group,
        $section = null,
        $scope = null,
        $scopeCode = null
    ) {
        if ($group->getId() !== 'paymob_payment') {
            return $result;
        }

        $allConfigs = $this->scopeConfig->getValue('payment', ScopeType::SCOPE_TYPE_DEFAULT);
        if (!is_array($allConfigs)) {
            return $result;
        }

        foreach ($allConfigs as $code => $config) {
            if (!str_starts_with($code, 'paymob_') || $code === 'paymob_payment') {
                continue;
            }

            $title = $config['title'] ?? $code;

            $dynamicFieldset = $fieldset->addFieldset(
                "{$code}_fieldset",
                [
                    'legend' => __('Paymob Method - %1', $title),
                    'collapsable' => true,
                    'class' => 'admin__fieldset'
                ]
            );

            $dynamicFieldset->addField("{$code}_active", 'select', [
                'label' => __('Enabled'),
                'name' => "groups[{$code}][fields][active][value]",
                'values' => [
                    ['value' => 1, 'label' => __('Yes')],
                    ['value' => 0, 'label' => __('No')]
                ],
                'value' => $config['active'] ?? 0,
                'container_class' => 'admin__field'
            ]);

            $dynamicFieldset->addField("{$code}_title", 'text', [
                'label' => __('Title'),
                'name' => "groups[{$code}][fields][title][value]",
                'value' => $config['title'] ?? '',
                'container_class' => 'admin__field'
            ]);
            $isMain = ($code === 'paymob_main');
            $dynamicFieldset->addField("{$code}_integration_id", 'text', [
                'label' => __('Integration ID'),
                'name' => "groups[{$code}][fields][integration_id][value]",
                'value' => $config['integration_id'] ?? '',
                'container_class' => 'admin__field',
                'note' => $isMain ? __('This is auto-generated by Paymob and you can change it.') : '',
                // 'disabled' => !$isMain,
                'disabled' => false, // Allow editing for all methods
            ]);

            $dynamicFieldset->addField("{$code}_description", 'text', [
                'label' => __('Description'),
                'name' => "groups[{$code}][fields][description][value]",
                'value' => $config['description'] ?? '',
                'container_class' => 'admin__field'
            ]);

            $dynamicFieldset->addField("{$code}_sort_order", 'text', [
                'label' => __('Sort Order'),
                'name' => "groups[{$code}][fields][sort_order][value]",
                'value' => $config['sort_order'] ?? '0',
                'container_class' => 'admin__field'
            ]);

            $dynamicFieldset->addField("{$code}_logo", 'image', [
                'label' => __('Logo'),
                'name' => "groups[{$code}][fields][logo][value]",
                'value' => isset($config['logo']) ? $this->getMediaUrl($config['logo']) : '',
                'note' => __('Upload a logo for this method.'),
                'container_class' => 'admin__field'
            ]);

            //new custom field from 2b development
            $dynamicFieldset->addField("{$code}_is_original_price", 'select', [
                'label' => __('Is Original Price'),
                'name' => "groups[{$code}][fields][is_original_price][value]",
                'values' => [
                    ['value' => 1, 'label' => __('Yes')],
                    ['value' => 0, 'label' => __('No')]
                ],
                'value' => $config['is_original_price'] ?? 0,
                'container_class' => 'admin__field'
            ]);

            $dynamicFieldset->addField("{$code}_discount_amount_percentage", 'text', [
                'label' => __('Discount Amount Percentage'),
                'name' => "groups[{$code}][fields][discount_amount_percentage][value]",
                'value' => $config['discount_amount_percentage'] ?? '0',
                'container_class' => 'admin__field',
                'note' => __('Enter discount percentage (e.g., 10 for 10%). Leave 0 for no discount.')
            ]);
            //end of new custom field from 2b development

        }

        return $result;
    }

    protected function getMediaUrl($file)
    {
        $baseMediaUrl = $this->scopeConfig->getValue(
            'web/unsecure/base_media_url',
            \Magento\Store\Model\ScopeInterface::SCOPE_STORE
        );

        return $baseMediaUrl . '/' . ltrim($file, '/');
    }

}
